{% set name = "pytorch-dp" %}
{% set version = "0.9.0" %}
{% set version_long = "0.1-beta.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/{{ name }}/archive/v{{ version_long }}.tar.gz
  sha256: 337d199abbaaacf576c0d952c094393cd69eacd924f0d9d18d5346eabd150c27

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - torchvision
    - scipy

test:
  imports:
    - torchdp

about:
  home: https://github.com/facebookresearch/pytorch-dp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: pytorch-dp is a library that enables training PyTorch models with differential privacy.
  description: |
    pytorch-dp is a library that enables training PyTorch models with differential privacy. It
    supports training with minimal code changes required on the client, has little impact on training
    performance and allows the client to online track the privacy budget expended at any given moment.
  doc_url: https://pypi.org/project/pytorch-dp/#description
  dev_url: https://github.com/facebookresearch/pytorch-dp

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - rluria14
    - oblute
